# Generated by Django 5.2.1 on 2025-11-04 01:50

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('autor', models.CharField(max_length=100, verbose_name='Autor')),
                ('genero', models.CharField(blank=True, max_length=50, verbose_name='Gênero')),
                ('disponivel', models.BooleanField(default=True)),
                ('capa_url', models.URLField(blank=True, max_length=500, null=True)),
                ('ano_publicacao', models.IntegerField(blank=True, null=True)),
                ('sinopse', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Empréstimo')),
                ('data_devolucao', models.DateTimeField(default=datetime.datetime(2025, 11, 11, 1, 50, 49, 985038, tzinfo=datetime.timezone.utc), verbose_name='Data de Devolução')),
                ('devolvido', models.BooleanField(default=False, verbose_name='Devolvido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acervo.livro', verbose_name='Livro')),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
            },
        ),
    ]
