# Generated by Django 5.2.1 on 2025-06-09 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0002_emprestimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_devolucao',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 16, 13, 27, 58, 759314, tzinfo=datetime.timezone.utc)),
        ),
    ]
