# Generated by Django 6.0.5 on 2026-05-12 19:15

import acervo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0003_alter_emprestimo_data_devolucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='codigo_isbn',
            field=models.CharField(blank=True, help_text='Código de barras ou ISBN do livro', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_devolucao',
            field=models.DateTimeField(default=acervo.models.Emprestimo.devolucao_padrao),
        ),
    ]
