# Generated by Django 6.0.5 on 2026-05-12 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0004_livro_codigo_isbn_alter_emprestimo_data_devolucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
    ]
